### ISSUE TITLE
Suggest moving Thread ID to double rather than Int

### ISSUE THREAD

**Issue by LiamBateman** [mathieukempe/HelpScoutNet#26]
Picked up the following error earlier: 

JSON integer 2147****** is too large or small for an Int32. Path 'item.threads[0].id', line 1, position 1237. 

Have resolved locally by adjusting Thread.cs Model parameter Id to double. 

Please let me know if you want me to submit a pull request.

**Comment by sergiopfaria** [comment]
Happening the same to us.

**Comment by LiamBateman** [comment]
Pull Request here - https://github.com/mathieukempe/HelpScoutNet/pull/27

@sergiopfaria this may solve your issue while awaiting the merge.

**Comment by sergiopfaria** [comment]
Thanks @LiamBateman 
Btw, helpScout is shutting down API 1.0 on June 6th, 2019.
Do you know if there any plans to update helpScoutNet to API 2.0?

**Comment by LiamBateman** [comment]
I wasn't aware of this, I'll have a look and see what the changes are and if I can help, I will.

**Comment by LiamBateman** [comment]
This is now resolved and can be closed
